version: 3

images:
  # Define the default image you want to build upon
  base_image:
    name: quay.io/acme_corp/aap-day2-ee:latest

# We leave the dependencies empty to keep it identical to the base

# This section adds custom commands to the build process
additional_build_steps:
  prepend_final:
    # These commands will download the latest virtctl binary, v1.6.3
    # place it in /usr/bin, and make it executable.
    - RUN curl -Lo /usr/bin/virtctl https://github.com/kubevirt/kubevirt/releases/download/v1.6.3/virtctl-v1.6.3-linux-amd64
    - RUN chmod +x /usr/bin/virtctl